name: tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
        laravel: [11, 12, 13]
        exclude:
          - php: 8.5
            laravel: 11
          - php: 8.2
            laravel: 13

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --dev --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --display-deprecations --fail-on-deprecation

  stub-tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        stack: [inertia, livewire]
        laravel: ['11.x-dev', '12.x-dev', '13.x-dev']

    name: Test Stubs - Laravel ${{ matrix.laravel }} - ${{ matrix.stack }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Setup Laravel
        run: |
          composer create-project laravel/laravel:${{ matrix.laravel }} .
          composer require laravel/jetstream:@dev --no-interaction --no-update
          composer config repositories.jetstream '{"type": "path", "url": "jetstream"}' --file composer.json

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: 'jetstream'
          persist-credentials: false

      - name: Install Jetstream
        run: |
          composer update "laravel/jetstream" --prefer-dist --no-interaction --no-progress -W
          php artisan jetstream:install ${{ matrix.stack }} --teams --api --verification --pest

      - name: Install NPM dependencies
        run: npm i

      - name: Compile assets
        run: npm run build

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
